### ISSUE TITLE
Some GLTF model load failed

### ISSUE THREAD

**Issue by conanlee88** [the3deer/android-3D-model-viewer#229]
I try to load the gltf model. Some of them load correctly, some load incorrectly, and some fail to load.
Below is the log of the error that failed to load.
`E/CrashReport: SIGSEGV(SEGV_MAPERR)
    0x7ffc80000
    #00    pc 000000000001df00    /system/lib64/libc.so (memcpy+880) [arm64-v8a::abf2cb59cb696c5ea6c7ad8d85799608]
    #01    pc 00000000001c0534    /vendor/lib64/egl/libGLESv2_adreno.so (_ZN20EsxVertexArrayObject18UpdateInternalVbosEPK17EsxDrawDescriptorjPK16EsxAttributeDesc+1580) [arm64-v8a::a56b0625c5af351c13a4b73623da17df]
    #02    pc 000000000032f998    /vendor/lib64/egl/libGLESv2_adreno.so (_ZN20A6xVertexArrayObject11CalcVfdRegsEPK17EsxDrawDescriptorP10A6xVfdRegs+72) [arm64-v8a::a56b0625c5af351c13a4b73623da17df]
    #03    pc 0000000000340ac4    /vendor/lib64/egl/libGLESv2_adreno.so (_ZN10A6xContext13ValidateStateEPK17EsxDrawDescriptor+1720) [arm64-v8a::a56b0625c5af351c13a4b73623da17df]
    #04    pc 00000000003353b4    /vendor/lib64/egl/libGLESv2_adreno.so (_ZN10A6xContext18HwValidateGfxStateEPK17EsxDrawDescriptor+16) [arm64-v8a::a56b0625c5af351c13a4b73623da17df]
    #05    pc 0000000000112ed4    /vendor/lib64/egl/libGLESv2_adreno.so (_ZN10EsxContext16ValidateGfxStateEPK17EsxDrawDescriptor+2192) [arm64-v8a::a56b0625c5af351c13a4b73623da17df]
    #06    pc 000000000010931c    /vendor/lib64/egl/libGLESv2_adreno.so (_ZN10EsxContext21DrawElementsInstancedE11EsxPrimTypej10EsxPixTypePKvji+996) [arm64-v8a::a56b0625c5af351c13a4b73623da17df]
    #07    pc 00000000000d5258    /system/lib64/libandroid_runtime.so [arm64-v8a::29ad66b350d5ef9362c92464e3401a7d]
    #08    pc 000000000105b7a4    /system/framework/arm64/boot-framework.oat (oatexec+7014308) [arm64-v8a::72121e6461776c4dd992a114ceb71376]
    java:
    org.the3deer.android_3d_model_engine.drawer.GLES20Renderer.drawObjectElement(GLES20Renderer.java:699)
    org.the3deer.android_3d_model_engine.drawer.GLES20Renderer.drawTrianglesUsingIndex(GLES20Renderer.java:559)
    org.the3deer.android_3d_model_engine.drawer.GLES20Renderer.drawShape(GLES20Renderer.java:491)
    org.the3deer.android_3d_model_engine.drawer.GLES20Renderer.draw(GLES20Renderer.java:314)
    org.the3deer.android_3d_model_engine.view.ModelRenderer.drawObject(ModelRenderer.java:881)
    org.the3deer.android_3d_model_engine.view.ModelRenderer.onDrawFrame(ModelRenderer.java:622)
    org.the3deer.android_3d_model_engine.view.ModelRenderer.onDrawFrame(ModelRenderer.java:501)
    android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
    android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)`

**Comment by conanlee88** [comment]
[scene.gltf.zip](https://github.com/the3deer/android-3D-model-viewer/files/10063078/scene.gltf.zip)
This is the file that failed to load

**Comment by andresoviedo** [comment]
Hi.  The model you provided is linked to the file scene.bin.  Fyi. you have other files missing 
Make sure you have at least the gltf and bin file 

`"buffers": [
    {
      "byteLength": 5721248,
      "uri": "scene.bin"
    }
  ],

"images": [
    {
      "uri": "textures/cactus-tree_u1_v1_baseColor.png"
    }
  ],`

Regards
