### ISSUE TITLE
The problem that the bounding box is not drawn

### ISSUE THREAD

**Issue by sunrin** [the3deer/android-3D-model-viewer#235]
In your example, the red and green cubes do not have bounding boxes drawn, 
and in my project, there are models with bounding boxes and others without.
Is there a rule for drawing a bounding box, or is the red and green cube in the example also drawing a bounding box?

**Comment by andresoviedo** [comment]
Hi @sunrin 
Please try the latest version for the new bounding box setting
If selected, all objects will be drawn using a white bounding box
If not selected, only the object you touch/select will render the bounding box ( touch again to unselect )
Hope that helps. Regards
