### ISSUE TITLE
Obj from local driver 

### ISSUE THREAD

**Issue by naren67n** [the3deer/android-3D-model-viewer#244]
When I press Android Explorer or File Explorer, it's not doing anything

**Comment by andresoviedo** [comment]
Hi @naren67n 

File Explorer is a legacy option only available for Android version <= 10

For the Android Explorer: it will first ask you for authorization.  
Hit again to open the Android Content Manager.

Hope that helps. Regards

**Comment by sounddrill31** [comment]
> Hi @naren67n
> 
> File Explorer is a legacy option only available for Android version <= 10
> 
> For the Android Explorer: it will first ask you for authorization. Hit again to open the Android Content Manager.
> 
> Hope that helps. Regards

Hi, I'm having the same issue - could you please re-open this? 

My device: g34 5g(fogos) with android 14
This happens on F-Droid version but also on play store version and even when I compile it myself targeting assembleDebug. 

Here's what I did: I installed it, opened it and selected "Load Model", and "Android Explorer". Please find a screenshot and a logcat output attached.

```cmd
adb logcat | findstr org.andresoviedo.dddmodel2 > output.txt
```
[output.txt](https://github.com/user-attachments/files/18266517/output.txt)



![Screenshot](https://github.com/user-attachments/assets/6dee6a2f-dbb7-495c-a836-382891efdaf6)
