### ISSUE TITLE
Project is not compiling at all.

### ISSUE THREAD

**Issue by momintahir** [the3deer/android-3D-model-viewer#245]
I am trying to compile this project. But it is full of errors. Any solution ?

<img width="1363" alt="Screenshot 2024-12-25 at 1 07 19 PM" src="https://github.com/user-attachments/assets/0ec2bb95-f592-4664-b174-18c9242c0f52" />

**Comment by andresoviedo** [comment]
Hi @momintahir 
I think I fixed the issue

Please do as instructed on the README (updated) to build the application and import the project into your Android Studio
You should have a similar output below

I tested it and it works on my ubuntu desktop

`$ git clone --recursive https://github.com/the3deer/android-3D-model-viewer.git
Cloning into 'android-3D-model-viewer'...
remote: Enumerating objects: 5170, done.
remote: Counting objects: 100% (145/145), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 5170 (delta 90), reused 59 (delta 59), pack-reused 5025 (from 2)
Receiving objects: 100% (5170/5170), 152.42 MiB | 4.04 MiB/s, done.
Resolving deltas: 100% (2370/2370), done.
Submodule 'engine' (https://github.com/the3deer/android-3D-engine.git) registered for path 'engine'
Cloning into '/home/andres/viewer6/android-3D-model-viewer/engine'...
remote: Enumerating objects: 2313, done.        
remote: Counting objects: 100% (2313/2313), done.        
remote: Compressing objects: 100% (1147/1147), done.        
remote: Total 2313 (delta 1054), reused 2264 (delta 1006), pack-reused 0 (from 0)        
Receiving objects: 100% (2313/2313), 6.20 MiB | 3.95 MiB/s, done.
Resolving deltas: 100% (1054/1054), done.
Submodule path 'engine': checked out 'c6eb265e5fdcc0f1f7f4d02a7562320d9470c465'
$ cd android-3D-model-viewer/
$ ./gradlew assembleDebug

> Task :engine:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :app:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/andres/viewer6/android-3D-model-viewer/app/src/main/java/org/the3deer/app/model3D/view/LoadDialogFragment.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

BUILD SUCCESSFUL in 10s
59 actionable tasks: 59 executed
$`
